version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
